### PR TITLE
get latest version of app using install.sh

### PR DESCRIPTION
**Pull request by emrullahcirit**

### CODE REVIEW

**Comment by bilgehannal** [comment]
Hello,
Thanks for the contribution,
I tried to run the version getting command below on linux and mac
`curl https://api.github.com/repos/bilgehannal/foldercode-cli/releases/latest|grep '"tag_name": '|cut -d 'v' -f 2|cut -d '"' -f 1`

* Unfortunately, it is not running on MacOS, it should be run on MacOS also.
* Can we use wget instead of curl. Reason is below:
    *  wget is more basic tool, some linux distros may have wget as opposed to curl
    * wget is using in installing, in the installing.sh, lets keep using wget, using two different tool for same purpose increases the dependency.

**Comment by emrullahcirit** [comment]
Can you check again, i use wget this time

**Comment by emrullahcirit** [comment]
btw, watch out back slash after "latest" word you should delete it because on macOS it puts back slash automatically. Normally there is no back slash on code. Thats why it is not working

**Comment by bilgehannal** [comment]
Alright,
It works like a charm, I am merging then, Iam going to close this issue.
Thanks for the contribution.

**Pull request merged**
